#!/usr/bin/env node
'use strict';
// 韌體源碼身分（single source of truth）。同一支演算法被兩端共用：
//   - build 端：sysid/fw_stamp.py (PlatformIO pre:) 呼 `--emit-header` 烤進 src/fw_identity.h
//   - server 端：server.js require 此模組重算 tree hash，與板子回報的 fw 比對
// 零雙實作 → 無漂移。srcHash 只依賴「實際編譯源碼內容」，不含時間/git → 同源同 hash，
// 跨重編譯穩定，這正是「燒錄韌體 vs 最新源碼是否相同」的可靠真相（git rev 在 dirty tree 失效）。
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const GENERATED_HEADER = path.join(ROOT, 'src', 'fw_identity.h');

// 影響韌體行為的編譯輸入。生成的身分 header 必須排除（否則循環依賴）。
const FW_EXT = new Set(['.c', '.cpp', '.cc', '.h', '.hpp', '.ino']);
const SRC_DIRS = ['src'];
const EXTRA_FILES = ['platformio.ini'];

function walk(dir, out) {
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, ent.name);
    if (ent.isDirectory()) walk(abs, out);
    else if (FW_EXT.has(path.extname(ent.name))) out.push(abs);
  }
}

function collectFiles() {
  const files = [];
  for (const dir of SRC_DIRS) {
    const abs = path.join(ROOT, dir);
    if (fs.existsSync(abs)) walk(abs, files);
  }
  for (const f of EXTRA_FILES) {
    const abs = path.join(ROOT, f);
    if (fs.existsSync(abs)) files.push(abs);
  }
  return files
    .filter((f) => f !== GENERATED_HEADER)
    .map((f) => path.relative(ROOT, f))
    .sort();  // 路徑排序 → 穩定順序，hash 可重現
}

function srcHash() {
  const rels = collectFiles();
  const h = crypto.createHash('sha256');
  for (const rel of rels) {
    h.update(rel, 'utf8');
    h.update('\0');
    h.update(fs.readFileSync(path.join(ROOT, rel)));
    h.update('\0');
  }
  return { hash: h.digest('hex').slice(0, 12), fileCount: rels.length, files: rels };
}

// trim=false 給 porcelain 用：其每行前 2 字元是 staged/worktree 狀態欄，
// 第一行的前導空格（=未 staged）會被 .trim() 吃掉而錯位，故 porcelain 不可 trim。
function git(args, fallback = null, trim = true) {
  try {
    const out = execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' });
    return trim ? out.trim() : out;
  } catch {
    return fallback;
  }
}

function gitInfo() {
  const rev = git(['rev-parse', '--short=9', 'HEAD'], 'nogit');
  const porcelain = git(['status', '--porcelain'], '', false);
  const allDirty = porcelain
    ? porcelain.split(/\r?\n/).filter(Boolean).map((l) => l.slice(3))
    : [];
  // 只有 firmware-relevant 的 dirt 才算 FW_DIRTY（前端/sysid 改動不影響燒錄韌體身分）。
  const dirtyFiles = allDirty.filter((f) => f.startsWith('src/') || f === 'platformio.ini');
  return { rev, dirty: dirtyFiles.length > 0, dirtyFiles, allDirty };
}

function computeIdentity() {
  const s = srcHash();
  const g = gitInfo();
  return {
    srcHash: s.hash,
    fileCount: s.fileCount,
    files: s.files,
    gitRev: g.rev,
    dirty: g.dirty,
    dirtyFiles: g.dirtyFiles,
    buildEpoch: Math.floor(Date.now() / 1000),
  };
}

function headerBody(id, epoch) {
  return [
    '// AUTO-GENERATED by sysid/fw_hash.js (PlatformIO pre-build). DO NOT EDIT; gitignored.',
    `#define FW_SRC_HASH "${id.srcHash}"`,
    `#define FW_GIT_REV "${id.gitRev}${id.dirty ? '+dirty' : ''}"`,
    `#define FW_DIRTY ${id.dirty ? 1 : 0}`,
    `#define FW_BUILD_EPOCH ${epoch}UL`,
    '',
  ].join('\n');
}

// 只在 srcHash/rev/dirty 變動時才覆寫 → no-op build 不動 header、不觸發 main.cpp 重編譯。
function emitHeader(target = GENERATED_HEADER) {
  const id = computeIdentity();
  const revStr = `${id.gitRev}${id.dirty ? '+dirty' : ''}`;
  try {
    const prev = fs.readFileSync(target, 'utf8');
    if (prev.includes(`#define FW_SRC_HASH "${id.srcHash}"`) &&
        prev.includes(`#define FW_GIT_REV "${revStr}"`)) {
      return { ...id, changed: false };
    }
  } catch { /* 無舊檔 → 寫新的 */ }
  fs.writeFileSync(target, headerBody(id, id.buildEpoch));
  return { ...id, changed: true };
}

if (require.main === module) {
  const arg = process.argv[2];
  if (arg === '--emit-header') {
    const r = emitHeader(process.argv[3] || GENERATED_HEADER);
    process.stderr.write(
      `[fw_hash] src=${r.srcHash} rev=${r.gitRev}${r.dirty ? '+dirty' : ''} files=${r.fileCount} ${r.changed ? '(written)' : '(unchanged)'}\n`
    );
  } else if (arg === '--raw') {
    process.stdout.write(computeIdentity().srcHash + '\n');
  } else {
    const id = computeIdentity();
    delete id.files;  // 預設輸出精簡；要全清單用 --files
    if (process.argv.includes('--files')) id.files = collectFiles();
    process.stdout.write(JSON.stringify(id, null, 2) + '\n');
  }
}

module.exports = { computeIdentity, srcHash, gitInfo, emitHeader };
