[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 460800
lib_deps =
    autowp/autowp-mcp2515@^1.2.1

[env:esp32_ota]
extends = env:esp32
upload_protocol = espota
upload_port = stewart.local
